# Docker filer for FUSIONprimerXL
# Arne Blom, 2024

# base image
FROM ubuntu:24.04
LABEL python_version="3.12" \ ViennaRNA_version="2.6.4" \ fastahack_version="1.0.0" \ primer3_version="2.6.1" \ bigBedToBed_version="2024-05-01" \ bowtie_version="1.3.1" \ bedtools_version="2.30.0"
# image is non-interactive ONLY DURING BUILD
ARG DEBIAN_FRONTEND=noninteractive

# install 'make' function (in build-essential & others from primer3 manual)
RUN apt-get update -y --fix-missing
RUN apt-get install -y --fix-missing build-essential g++ cmake git-all
RUN apt-get install -y wget
RUN apt-get install -y unzip
RUN apt-get install -y python3
RUN apt-get install -y python3-pip

# install python packages
RUN python3 -m pip config set global.break-system-packages true
RUN python3 -m pip install -U pip Bio
RUN python3 -m pip install -U matplotlib jupyterlab
RUN python3 -m pip install -U pandas
RUN python3 -m pip install -U datetime
RUN python3 -m pip install -U pybedtools

# Primer3
WORKDIR /bin
RUN wget https://github.com/primer3-org/primer3/archive/refs/tags/v2.6.1.zip
RUN unzip v2.6.1.zip
WORKDIR /bin/primer3-2.6.1/src
RUN make all
RUN mv primer3_core /bin/primer3_core
WORKDIR /bin
RUN rm -rf primer3-2.6.1 v2.6.1.zip

# nupack
# ADD ./nupack-4.0.1.9.zip /bin/
# RUN unzip nupack-4.0.1.9
# RUN python3 -m pip install -U nupack -f ./nupack-4.0.1.9/package

# ViennaRNA (RNAfold)
RUN wget https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_6_x/ViennaRNA-2.6.4.tar.gz
RUN tar -xvzf ViennaRNA-2.6.4.tar.gz
WORKDIR /bin/ViennaRNA-2.6.4
RUN ./configure
RUN make
RUN make install
WORKDIR /bin 
RUN rm -rf ViennaRNA-2.6.4 ViennaRNA-2.6.4.tar.gz

# fastahack
RUN wget https://github.com/ekg/fastahack/archive/refs/tags/v1.0.0.zip
RUN unzip v1.0.0.zip
WORKDIR /bin/fastahack-1.0.0
RUN make all
RUN make install
RUN mv fastahack /bin
WORKDIR /bin
RUN rm -rf fastahack-1.0.0 v1.0.0.zip

# bigBedToBed dependencies
RUN apt-get install -y libkrb5-3 curl

# bigBedToBed
RUN wget https://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bigBedToBed
RUN chmod +x bigBedToBed

# bowtie (1.3.1)
RUN apt-get install -y bowtie

# bedtools
RUN apt-get install -y bedtools
RUN rm -rf /var/lib/apt/lists/*

# scripts
WORKDIR /
ADD scripts /usr/bin
RUN chmod +x /usr/bin/00_A_gtf_to_bed.py /usr/bin/00_B_validate_bed.py /usr/bin/00_C_generate_ENST_list.py /usr/bin/00_validate_bed.py /usr/bin/01_split_fusionRNAs.py /usr/bin/02_Sequence_retrieval_chrom_pos.py /usr/bin/03_generate_in_files.py /usr/bin/04_get_SNPs.py /usr/bin/05_get_sec_str_temp.py /usr/bin/06_primer3.py /usr/bin/06_upfront_filter.py /usr/bin/07_split_primers.py /usr/bin/08_get_sec_str_amp.py /usr/bin/09_filter.py /usr/bin/10_gather_output.py /usr/bin/11_summary_run.py /usr/bin/Nupack_amp.py /usr/bin/Nupack_temp.py
